# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Print_Host_Details
  displayName: 'Print Host Details'
  pool:
    name: MySelfHostedPool  # Replace with the name of your self-hosted pool
  steps:
  - script: echo "Host Details:$(hostname)"
    displayName: 'Print Hostname'
  - script: echo "IP Address:$(hostname -i)"
    displayName: 'Print IP Address'

